cleanup

diff --git a/security/auth-proxy-ha-github-orga.yaml b/security/auth-proxy-ha-github-orga.yaml
--- a/security/auth-proxy-ha-github-orga.yaml
+++ b/security/auth-proxy-ha-github-orga.yaml
@@ -257,12 +257,11 @@ Resources:
               newrelic-sysmond: 'https://download.newrelic.com/pub/newrelic/el5/x86_64/newrelic-sysmond-2.3.0.132-1.x86_64.rpm'
           files:
             '/etc/newrelic/nrsysmond.cfg':
-              content:
-                !Sub |
-                  license_key=${NewRelicLicenseKey}
-                  loglevel=info
-                  logfile=/var/log/newrelic/nrsysmond.log
-                  labels=StackName:${AWS::StackName};AccountId:${AWS::AccountId};Region:${AWS::Region}
+              content: !Sub |
+                license_key=${NewRelicLicenseKey}
+                loglevel=info
+                logfile=/var/log/newrelic/nrsysmond.log
+                labels=StackName:${AWS::StackName};AccountId:${AWS::AccountId};Region:${AWS::Region}
               mode: '000640'
               owner: root
               group: newrelic
@@ -276,31 +275,29 @@ Resources:
         ssh-access:
           files:
             '/opt/authorized_keys_command.sh':
-              content:
-                !Sub |
-                  #!/bin/bash -e
-                  if [ -z "$1" ]; then
-                    exit 1
-                  fi
-                  aws iam list-ssh-public-keys --user-name "$1" --query "SSHPublicKeys[?Status == 'Active'].[SSHPublicKeyId]" --output text | while read KeyId;
-                  do
-                    aws iam get-ssh-public-key --user-name "$1" --ssh-public-key-id "$KeyId" --encoding SSH --query "SSHPublicKey.SSHPublicKeyBody" --output text
-                  done
+              content: !Sub |
+                #!/bin/bash -e
+                if [ -z "$1" ]; then
+                  exit 1
+                fi
+                aws iam list-ssh-public-keys --user-name "$1" --query "SSHPublicKeys[?Status == 'Active'].[SSHPublicKeyId]" --output text | while read KeyId;
+                do
+                  aws iam get-ssh-public-key --user-name "$1" --ssh-public-key-id "$KeyId" --encoding SSH --query "SSHPublicKey.SSHPublicKeyBody" --output text
+                done
               mode: '000755'
               owner: root
               group: root
             '/opt/import_users.sh':
-              content:
-                !Sub |
-                  #!/bin/bash
-                  aws iam list-users --query "Users[].[UserName]" --output text | while read User; do
-                    if id -u "$User" >/dev/null 2>&1; then
-                      echo "$User exists"
-                    else
-                      /usr/sbin/adduser "$User"
-                      echo "$User ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/$User"
-                    fi
-                  done
+              content: !Sub |
+                #!/bin/bash
+                aws iam list-users --query "Users[].[UserName]" --output text | while read User; do
+                  if id -u "$User" >/dev/null 2>&1; then
+                    echo "$User exists"
+                  else
+                    /usr/sbin/adduser "$User"
+                    echo "$User ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/$User"
+                  fi
+                done
               mode: '000755'
               owner: root
               group: root
@@ -336,219 +333,205 @@ Resources:
               awslogs: []
           files:
             '/etc/oauth2_proxy.cfg':
-              content:
-                !Sub |
-                  ## OAuth2 Proxy Config File
-                  ## https://github.com/bitly/oauth2_proxy
-                  http_address = "0.0.0.0:4180"
-                  upstreams = [
-                    "${Upstream}"
-                  ]
-                  request_logging = false
-                  pass_basic_auth = false
-                  email_domains = [
-                    "*"
-                  ]
-                  client_id = "${GitHubClientId}"
-                  client_secret = "${GitHubClientSecret}"
-                  cookie_secret = "${CookieSecret}"
-                  provider = "github"
-                  github-team = "${GitHubOrganization}"
+              content: !Sub |
+                ## OAuth2 Proxy Config File
+                ## https://github.com/bitly/oauth2_proxy
+                http_address = "0.0.0.0:4180"
+                upstreams = [
+                  "${Upstream}"
+                ]
+                request_logging = false
+                pass_basic_auth = false
+                email_domains = [
+                  "*"
+                ]
+                client_id = "${GitHubClientId}"
+                client_secret = "${GitHubClientSecret}"
+                cookie_secret = "${CookieSecret}"
+                provider = "github"
+                github-team = "${GitHubOrganization}"
               mode: '000644'
               owner: root
               group: root
             '/etc/init.d/oauth2_proxy':
-              content:
-                !Sub |
-                  #!/bin/sh
-                  ### BEGIN INIT INFO
-                  # Provides:
-                  # Required-Start:    $remote_fs $syslog
-                  # Required-Stop:     $remote_fs $syslog
-                  # Default-Start:     2 3 4 5
-                  # Default-Stop:      0 1 6
-                  # Short-Description: Start daemon at boot time
-                  # Description:       Enable service provided by daemon.
-                  ### END INIT INFO
-
-                  dir="/opt/oauth2_proxy/oauth2_proxy-2.1.linux-amd64.go1.6"
-                  cmd="./oauth2_proxy -config=/etc/oauth2_proxy.cfg"
-                  user="oauth2_proxy"
-
-                  name=`basename $0`
-                  pid_file="/var/run/$name.pid"
-                  stdout_log="/var/log/$name.log"
-                  stderr_log="/var/log/$name.err"
-
-                  get_pid() {
-                      cat "$pid_file"
-                  }
-
-                  is_running() {
-                      [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
-                  }
-
-                  case "$1" in
-                      start)
-                      if is_running; then
-                          echo "Already started"
-                      else
-                          echo "Starting $name"
-                          cd "$dir"
-                          if [ -z "$user" ]; then
-                              sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
-                          else
-                              sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
-                          fi
-                          echo $! > "$pid_file"
-                          if ! is_running; then
-                              echo "Unable to start, see $stdout_log and $stderr_log"
-                              exit 1
-                          fi
-                      fi
-                      ;;
-                      stop)
-                      if is_running; then
-                          echo -n "Stopping $name.."
-                          kill `get_pid`
-                          for i in {1..10}
-                          do
-                              if ! is_running; then
-                                  break
-                              fi
-
-                              echo -n "."
-                              sleep 1
-                          done
-                          echo
-
-                          if is_running; then
-                              echo "Not stopped; may still be shutting down or shutdown may have failed"
-                              exit 1
-                          else
-                              echo "Stopped"
-                              if [ -f "$pid_file" ]; then
-                                  rm "$pid_file"
-                              fi
-                          fi
-                      else
-                          echo "Not running"
-                      fi
-                      ;;
-                      restart)
-                      $0 stop
-                      if is_running; then
-                          echo "Unable to stop, will not attempt to start"
-                          exit 1
-                      fi
-                      $0 start
-                      ;;
-                      status)
-                      if is_running; then
-                          echo "Running"
-                      else
-                          echo "Stopped"
-                          exit 1
-                      fi
-                      ;;
-                      *)
-                      echo "Usage: $0 {start|stop|restart|status}"
-                      exit 1
-                      ;;
-                  esac
-
-                  exit 0
+              content: !Sub |
+                #!/bin/sh
+                ### BEGIN INIT INFO
+                # Provides:
+                # Required-Start:    $remote_fs $syslog
+                # Required-Stop:     $remote_fs $syslog
+                # Default-Start:     2 3 4 5
+                # Default-Stop:      0 1 6
+                # Short-Description: Start daemon at boot time
+                # Description:       Enable service provided by daemon.
+                ### END INIT INFO
+                dir="/opt/oauth2_proxy/oauth2_proxy-2.1.linux-amd64.go1.6"
+                cmd="./oauth2_proxy -config=/etc/oauth2_proxy.cfg"
+                user="oauth2_proxy"
+                name=`basename $0`
+                pid_file="/var/run/$name.pid"
+                stdout_log="/var/log/$name.log"
+                stderr_log="/var/log/$name.err"
+                get_pid() {
+                    cat "$pid_file"
+                }
+                is_running() {
+                    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
+                }
+                case "$1" in
+                    start)
+                    if is_running; then
+                        echo "Already started"
+                    else
+                        echo "Starting $name"
+                        cd "$dir"
+                        if [ -z "$user" ]; then
+                            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
+                        else
+                            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
+                        fi
+                        echo $! > "$pid_file"
+                        if ! is_running; then
+                            echo "Unable to start, see $stdout_log and $stderr_log"
+                            exit 1
+                        fi
+                    fi
+                    ;;
+                    stop)
+                    if is_running; then
+                        echo -n "Stopping $name.."
+                        kill `get_pid`
+                        for i in {1..10}
+                        do
+                            if ! is_running; then
+                                break
+                            fi
+                            echo -n "."
+                            sleep 1
+                        done
+                        echo
+                        if is_running; then
+                            echo "Not stopped; may still be shutting down or shutdown may have failed"
+                            exit 1
+                        else
+                            echo "Stopped"
+                            if [ -f "$pid_file" ]; then
+                                rm "$pid_file"
+                            fi
+                        fi
+                    else
+                        echo "Not running"
+                    fi
+                    ;;
+                    restart)
+                    $0 stop
+                    if is_running; then
+                        echo "Unable to stop, will not attempt to start"
+                        exit 1
+                    fi
+                    $0 start
+                    ;;
+                    status)
+                    if is_running; then
+                        echo "Running"
+                    else
+                        echo "Stopped"
+                        exit 1
+                    fi
+                    ;;
+                    *)
+                    echo "Usage: $0 {start|stop|restart|status}"
+                    exit 1
+                    ;;
+                esac
+                exit 0
               mode: '000755'
               owner: root
               group: root
             '/etc/awslogs/awscli.conf':
-              content:
-                !Sub |
-                  [default]
-                  region = ${AWS::Region}
-                  [plugins]
-                  cwlogs = cwlogs
+              content: !Sub |
+                [default]
+                region = ${AWS::Region}
+                [plugins]
+                cwlogs = cwlogs
               mode: '000644'
               owner: root
               group: root
             '/etc/awslogs/awslogs.conf':
-              content:
-                !Sub |
-                  [general]
-                  state_file = /var/lib/awslogs/agent-state
-                  [/var/log/messages]
-                  datetime_format = %b %d %H:%M:%S
-                  file = /var/log/messages
-                  log_stream_name = {instance_id}/var/log/messages
-                  log_group_name = ${Logs}
-                  [/var/log/secure]
-                  datetime_format = %b %d %H:%M:%S
-                  file = /var/log/secure
-                  log_stream_name = {instance_id}/var/log/secure
-                  log_group_name = ${Logs}
-                  [/var/log/cron]
-                  datetime_format = %b %d %H:%M:%S
-                  file = /var/log/cron
-                  log_stream_name = {instance_id}/var/log/cron
-                  log_group_name = ${Logs}
-                  [/var/log/cloud-init.log]
-                  datetime_format = %b %d %H:%M:%S
-                  file = /var/log/cloud-init.log
-                  log_stream_name = {instance_id}/var/log/cloud-init.log
-                  log_group_name = ${Logs}
-                  [/var/log/cfn-init.log]
-                  datetime_format = %Y-%m-%d %H:%M:%S
-                  file = /var/log/cfn-init.log
-                  log_stream_name = {instance_id}/var/log/cfn-init.log
-                  log_group_name = ${Logs}
-                  [/var/log/cfn-hup.log]
-                  datetime_format = %Y-%m-%d %H:%M:%S
-                  file = /var/log/cfn-hup.log
-                  log_stream_name = {instance_id}/var/log/cfn-hup.log
-                  log_group_name = ${Logs}
-                  [/var/log/cfn-init-cmd.log]
-                  datetime_format = %Y-%m-%d %H:%M:%S
-                  file = /var/log/cfn-init-cmd.log
-                  log_stream_name = {instance_id}/var/log/cfn-init-cmd.log
-                  log_group_name = ${Logs}
-                  [/var/log/cloud-init-output.log]
-                  file = /var/log/cloud-init-output.log
-                  log_stream_name = {instance_id}/var/log/cloud-init-output.log
-                  log_group_name = ${Logs}
-                  [/var/log/dmesg]
-                  file = /var/log/dmesg
-                  log_stream_name = {instance_id}/var/log/dmesg
-                  log_group_name = ${Logs}
-                  [/var/log/oauth2_proxy.log]
-                  file = /var/log/oauth2_proxy.log
-                  log_stream_name = {instance_id}/var/log/oauth2_proxy.log
-                  log_group_name = ${Logs}
-                  [/var/log/oauth2_proxy.err]
-                  datetime_format = %Y/%m/%d %H:%M:%S
-                  file = /var/log/oauth2_proxy.err
-                  log_stream_name = {instance_id}/var/log/oauth2_proxy.err
-                  log_group_name = ${Logs}
+              content: !Sub |
+                [general]
+                state_file = /var/lib/awslogs/agent-state
+                [/var/log/messages]
+                datetime_format = %b %d %H:%M:%S
+                file = /var/log/messages
+                log_stream_name = {instance_id}/var/log/messages
+                log_group_name = ${Logs}
+                [/var/log/secure]
+                datetime_format = %b %d %H:%M:%S
+                file = /var/log/secure
+                log_stream_name = {instance_id}/var/log/secure
+                log_group_name = ${Logs}
+                [/var/log/cron]
+                datetime_format = %b %d %H:%M:%S
+                file = /var/log/cron
+                log_stream_name = {instance_id}/var/log/cron
+                log_group_name = ${Logs}
+                [/var/log/cloud-init.log]
+                datetime_format = %b %d %H:%M:%S
+                file = /var/log/cloud-init.log
+                log_stream_name = {instance_id}/var/log/cloud-init.log
+                log_group_name = ${Logs}
+                [/var/log/cfn-init.log]
+                datetime_format = %Y-%m-%d %H:%M:%S
+                file = /var/log/cfn-init.log
+                log_stream_name = {instance_id}/var/log/cfn-init.log
+                log_group_name = ${Logs}
+                [/var/log/cfn-hup.log]
+                datetime_format = %Y-%m-%d %H:%M:%S
+                file = /var/log/cfn-hup.log
+                log_stream_name = {instance_id}/var/log/cfn-hup.log
+                log_group_name = ${Logs}
+                [/var/log/cfn-init-cmd.log]
+                datetime_format = %Y-%m-%d %H:%M:%S
+                file = /var/log/cfn-init-cmd.log
+                log_stream_name = {instance_id}/var/log/cfn-init-cmd.log
+                log_group_name = ${Logs}
+                [/var/log/cloud-init-output.log]
+                file = /var/log/cloud-init-output.log
+                log_stream_name = {instance_id}/var/log/cloud-init-output.log
+                log_group_name = ${Logs}
+                [/var/log/dmesg]
+                file = /var/log/dmesg
+                log_stream_name = {instance_id}/var/log/dmesg
+                log_group_name = ${Logs}
+                [/var/log/oauth2_proxy.log]
+                file = /var/log/oauth2_proxy.log
+                log_stream_name = {instance_id}/var/log/oauth2_proxy.log
+                log_group_name = ${Logs}
+                [/var/log/oauth2_proxy.err]
+                datetime_format = %Y/%m/%d %H:%M:%S
+                file = /var/log/oauth2_proxy.err
+                log_stream_name = {instance_id}/var/log/oauth2_proxy.err
+                log_group_name = ${Logs}
               mode: '000644'
               owner: root
               group: root
             '/etc/cfn/cfn-hup.conf':
-              content:
-                !Sub |
-                  [main]
-                  stack=${AWS::StackId}
-                  region=${AWS::Region}
-                  interval=1
+              content: !Sub |
+                [main]
+                stack=${AWS::StackId}
+                region=${AWS::Region}
+                interval=1
               mode: '000400'
               owner: root
               group: root
             '/etc/cfn/hooks.d/cfn-auto-reloader.conf':
-              content:
-                !Sub |
-                  [cfn-auto-reloader-hook]
-                  triggers=post.update
-                  path=Resources.LaunchConfiguration.Metadata.AWS::CloudFormation::Init
-                  action=/opt/aws/bin/cfn-init --verbose --stack=${AWS::StackName} --region=${AWS::Region} --resource=LaunchConfiguration
-                  runas=root
+              content: !Sub |
+                [cfn-auto-reloader-hook]
+                triggers=post.update
+                path=Resources.LaunchConfiguration.Metadata.AWS::CloudFormation::Init
+                action=/opt/aws/bin/cfn-init --verbose --stack=${AWS::StackName} --region=${AWS::Region} --resource=LaunchConfiguration
+                runas=root
           services:
             sysvinit:
               awslogs:
